name: Docker Compose Test

on:
  push:
    branches: [ main ]
    paths:
      - 'docker-compose.yml'
      - 'docker/flink/**'
      - 'etc/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker-compose.yml'
      - 'docker/flink/**'
      - 'etc/**'

jobs:
  test-docker-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Flink image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/flink
          push: false
          tags: cdc-lab-flink:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start services
        run: |
          # Start only the essential services for testing
          docker compose up -d postgres zookeeper kafka schema-registry connect iceberg-rest trino kafka-ui
          # Wait for services to be healthy
          timeout 300 bash -c 'until docker compose ps | grep -q "healthy\|running"; do sleep 5; done'

      - name: Test service connectivity
        run: |
          # Test PostgreSQL connection
          docker compose exec -T postgres pg_isready -U appuser -d appdb

          # Test Kafka connectivity
          docker compose exec -T kafka kafka-broker-api-versions --bootstrap-server localhost:9092

          # Test Schema Registry
          curl -f http://localhost:8081/subjects

          # Test Trino connectivity
          docker compose exec -T trino trino --execute "SELECT 1"

          # Test Iceberg REST catalog
          curl -f http://localhost:8181/v1/config

      - name: Test Kafka Connect
        run: |
          # Test Kafka Connect REST API
          curl -f http://localhost:8083/connectors

      - name: Clean up
        if: always()
        run: docker compose down -v