name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: |
            ## CDC Lab Release ${{ steps.get_version.outputs.version }}

            ### What's Changed
            This release includes updates to the CDC lab environment and configurations.

            ### Components
            - PostgreSQL CDC setup
            - Kafka and Schema Registry configuration
            - Flink streaming jobs
            - Iceberg table management
            - Trino analytics queries

            ### Deployment
            ```bash
            # Start the lab environment
            docker compose up -d

            # Deploy connector
            ./scripts/deploy-connector.sh

            # Run demos
            ./scripts/run-demo.sh
            ```

            For detailed setup instructions, see the [README](README.md).
          draft: false
          prerelease: false

  build-and-push-docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/flink
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push Flink image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/flink
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max