name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install fastavro
      - name: Validate Avro Schemas
        run: python ci/validate_schemas.py

  validate-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Docker Compose configuration
        run: docker compose config --quiet

  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check SQL files syntax
        run: |
          # Basic SQL syntax check for Flink SQL files
          find sql -name "*.sql" -type f -exec echo "Checking {}" \; -exec head -5 {} \;

  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON files
        run: |
          # Validate JSON files in connectors directory
          find connectors -name "*.json" -type f -exec echo "Validating {}" \; -exec python -m json.tool {} \; >/dev/null \;

  check-file-permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for executable files
        run: |
          # Check for files that should be executable
          executable_files=("scripts/deploy-connector.sh" "scripts/run-demo.sh")
          for file in "${executable_files[@]}"; do
            if [[ -f "$file" ]]; then
              if [[ ! -x "$file" ]]; then
                echo "File $file should be executable"
                exit 1
              fi
            fi
          done
          echo "All required files have correct permissions"